/**
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.uniluebeck.isp.tessla.xtext.TeSSLaRuntimeModule;
import de.uniluebeck.isp.tessla.xtext.TeSSLaStandaloneSetup;
import de.uniluebeck.isp.tessla.xtext.ide.TeSSLaIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class TeSSLaIdeSetup extends TeSSLaStandaloneSetup {
  @Override
  public Injector createInjector() {
    TeSSLaRuntimeModule _teSSLaRuntimeModule = new TeSSLaRuntimeModule();
    TeSSLaIdeModule _teSSLaIdeModule = new TeSSLaIdeModule();
    return Guice.createInjector(Modules2.mixin(_teSSLaRuntimeModule, _teSSLaIdeModule));
  }
}
