/**
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.xtext.teSSLa;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>arg</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.uniluebeck.isp.tessla.xtext.teSSLa.arg#getArg <em>Arg</em>}</li>
 *   <li>{@link de.uniluebeck.isp.tessla.xtext.teSSLa.arg#getExp <em>Exp</em>}</li>
 * </ul>
 *
 * @see de.uniluebeck.isp.tessla.xtext.teSSLa.TeSSLaPackage#getarg()
 * @model
 * @generated
 */
public interface arg extends EObject
{
  /**
   * Returns the value of the '<em><b>Arg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Arg</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg</em>' attribute.
   * @see #setArg(String)
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.TeSSLaPackage#getarg_Arg()
   * @model
   * @generated
   */
  String getArg();

  /**
   * Sets the value of the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.arg#getArg <em>Arg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arg</em>' attribute.
   * @see #getArg()
   * @generated
   */
  void setArg(String value);

  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exp</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(typedExpression)
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.TeSSLaPackage#getarg_Exp()
   * @model containment="true"
   * @generated
   */
  typedExpression getExp();

  /**
   * Sets the value of the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.arg#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(typedExpression value);

} // arg
