/**
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.xtext.teSSLa;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.uniluebeck.isp.tessla.xtext.teSSLa.IfStatement#getIf <em>If</em>}</li>
 *   <li>{@link de.uniluebeck.isp.tessla.xtext.teSSLa.IfStatement#getThen <em>Then</em>}</li>
 *   <li>{@link de.uniluebeck.isp.tessla.xtext.teSSLa.IfStatement#getElse <em>Else</em>}</li>
 * </ul>
 *
 * @see de.uniluebeck.isp.tessla.xtext.teSSLa.TeSSLaPackage#getIfStatement()
 * @model
 * @generated
 */
public interface IfStatement extends expression
{
  /**
   * Returns the value of the '<em><b>If</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>If</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>If</em>' containment reference.
   * @see #setIf(typedExpression)
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.TeSSLaPackage#getIfStatement_If()
   * @model containment="true"
   * @generated
   */
  typedExpression getIf();

  /**
   * Sets the value of the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.IfStatement#getIf <em>If</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>If</em>' containment reference.
   * @see #getIf()
   * @generated
   */
  void setIf(typedExpression value);

  /**
   * Returns the value of the '<em><b>Then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Then</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then</em>' containment reference.
   * @see #setThen(typedExpression)
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.TeSSLaPackage#getIfStatement_Then()
   * @model containment="true"
   * @generated
   */
  typedExpression getThen();

  /**
   * Sets the value of the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.IfStatement#getThen <em>Then</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then</em>' containment reference.
   * @see #getThen()
   * @generated
   */
  void setThen(typedExpression value);

  /**
   * Returns the value of the '<em><b>Else</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Else</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else</em>' containment reference.
   * @see #setElse(typedExpression)
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.TeSSLaPackage#getIfStatement_Else()
   * @model containment="true"
   * @generated
   */
  typedExpression getElse();

  /**
   * Sets the value of the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.IfStatement#getElse <em>Else</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Else</em>' containment reference.
   * @see #getElse()
   * @generated
   */
  void setElse(typedExpression value);

} // IfStatement
