/**
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.xtext.teSSLa;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.uniluebeck.isp.tessla.xtext.teSSLa.Operation#getLeft <em>Left</em>}</li>
 *   <li>{@link de.uniluebeck.isp.tessla.xtext.teSSLa.Operation#getOp <em>Op</em>}</li>
 *   <li>{@link de.uniluebeck.isp.tessla.xtext.teSSLa.Operation#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see de.uniluebeck.isp.tessla.xtext.teSSLa.TeSSLaPackage#getOperation()
 * @model
 * @generated
 */
public interface Operation extends expression
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(expression)
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.TeSSLaPackage#getOperation_Left()
   * @model containment="true"
   * @generated
   */
  expression getLeft();

  /**
   * Sets the value of the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.Operation#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(expression value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Op</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.TeSSLaPackage#getOperation_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.Operation#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(value)
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.TeSSLaPackage#getOperation_Right()
   * @model containment="true"
   * @generated
   */
  value getRight();

  /**
   * Sets the value of the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.Operation#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(value value);

} // Operation
