/**
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.xtext.teSSLa;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>out</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.uniluebeck.isp.tessla.xtext.teSSLa.out#getExp <em>Exp</em>}</li>
 *   <li>{@link de.uniluebeck.isp.tessla.xtext.teSSLa.out#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see de.uniluebeck.isp.tessla.xtext.teSSLa.TeSSLaPackage#getout()
 * @model
 * @generated
 */
public interface out extends EObject
{
  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exp</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(typedExpression)
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.TeSSLaPackage#getout_Exp()
   * @model containment="true"
   * @generated
   */
  typedExpression getExp();

  /**
   * Sets the value of the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.out#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(typedExpression value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.TeSSLaPackage#getout_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.out#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // out
