/**
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.xtext.teSSLa;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.uniluebeck.isp.tessla.xtext.teSSLa.TeSSLaFactory
 * @model kind="package"
 * @generated
 */
public interface TeSSLaPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "teSSLa";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.uniluebeck.de/isp/tessla/xtext/TeSSLa";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "teSSLa";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TeSSLaPackage eINSTANCE = de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl.init();

  /**
   * The meta object id for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.ModelImpl
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Spec</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__SPEC = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.StatementImpl
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The feature id for the '<em><b>Def</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__DEF = 0;

  /**
   * The feature id for the '<em><b>Out</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__OUT = 1;

  /**
   * The feature id for the '<em><b>In</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__IN = 2;

  /**
   * The feature id for the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__COMMENT = 3;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.definitionImpl <em>definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.definitionImpl
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#getdefinition()
   * @generated
   */
  int DEFINITION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__NAME = 0;

  /**
   * The feature id for the '<em><b>Param List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__PARAM_LIST = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__TYPE = 2;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__EXPRESSION = 3;

  /**
   * The number of structural features of the '<em>definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.paramListImpl <em>param List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.paramListImpl
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#getparamList()
   * @generated
   */
  int PARAM_LIST = 3;

  /**
   * The feature id for the '<em><b>Params</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_LIST__PARAMS = 0;

  /**
   * The feature id for the '<em><b>Types</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_LIST__TYPES = 1;

  /**
   * The number of structural features of the '<em>param List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_LIST_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.outImpl <em>out</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.outImpl
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#getout()
   * @generated
   */
  int OUT = 4;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUT__EXP = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUT__NAME = 1;

  /**
   * The number of structural features of the '<em>out</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.inImpl <em>in</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.inImpl
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#getin()
   * @generated
   */
  int IN = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IN__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IN__TYPE = 1;

  /**
   * The number of structural features of the '<em>in</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IN_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.typedExpressionImpl <em>typed Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.typedExpressionImpl
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#gettypedExpression()
   * @generated
   */
  int TYPED_EXPRESSION = 6;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPED_EXPRESSION__EXP = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPED_EXPRESSION__TYPE = 1;

  /**
   * The number of structural features of the '<em>typed Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPED_EXPRESSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.expressionImpl <em>expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.expressionImpl
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#getexpression()
   * @generated
   */
  int EXPRESSION = 7;

  /**
   * The number of structural features of the '<em>expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.valueImpl <em>value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.valueImpl
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#getvalue()
   * @generated
   */
  int VALUE = 8;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__OP = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__EXP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__STATEMENTS = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__NAME = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__ARGS = EXPRESSION_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.argImpl <em>arg</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.argImpl
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#getarg()
   * @generated
   */
  int ARG = 9;

  /**
   * The feature id for the '<em><b>Arg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARG__ARG = 0;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARG__EXP = 1;

  /**
   * The number of structural features of the '<em>arg</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARG_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.IfStatementImpl <em>If Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.IfStatementImpl
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#getIfStatement()
   * @generated
   */
  int IF_STATEMENT = 10;

  /**
   * The feature id for the '<em><b>If</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STATEMENT__IF = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STATEMENT__THEN = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Else</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STATEMENT__ELSE = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>If Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STATEMENT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.OperationImpl
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 11;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__OP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;


  /**
   * Returns the meta object for class '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.Model#getSpec <em>Spec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Spec</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.Model#getSpec()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Spec();

  /**
   * Returns the meta object for class '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for the containment reference '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.Statement#getDef <em>Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Def</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.Statement#getDef()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Def();

  /**
   * Returns the meta object for the containment reference '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.Statement#getOut <em>Out</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Out</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.Statement#getOut()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Out();

  /**
   * Returns the meta object for the containment reference '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.Statement#getIn <em>In</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>In</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.Statement#getIn()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_In();

  /**
   * Returns the meta object for the attribute '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.Statement#getComment <em>Comment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comment</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.Statement#getComment()
   * @see #getStatement()
   * @generated
   */
  EAttribute getStatement_Comment();

  /**
   * Returns the meta object for class '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.definition <em>definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>definition</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.definition
   * @generated
   */
  EClass getdefinition();

  /**
   * Returns the meta object for the attribute '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.definition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.definition#getName()
   * @see #getdefinition()
   * @generated
   */
  EAttribute getdefinition_Name();

  /**
   * Returns the meta object for the containment reference '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.definition#getParamList <em>Param List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Param List</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.definition#getParamList()
   * @see #getdefinition()
   * @generated
   */
  EReference getdefinition_ParamList();

  /**
   * Returns the meta object for the attribute '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.definition#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.definition#getType()
   * @see #getdefinition()
   * @generated
   */
  EAttribute getdefinition_Type();

  /**
   * Returns the meta object for the containment reference '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.definition#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.definition#getExpression()
   * @see #getdefinition()
   * @generated
   */
  EReference getdefinition_Expression();

  /**
   * Returns the meta object for class '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.paramList <em>param List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>param List</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.paramList
   * @generated
   */
  EClass getparamList();

  /**
   * Returns the meta object for the attribute list '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.paramList#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Params</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.paramList#getParams()
   * @see #getparamList()
   * @generated
   */
  EAttribute getparamList_Params();

  /**
   * Returns the meta object for the attribute list '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.paramList#getTypes <em>Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Types</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.paramList#getTypes()
   * @see #getparamList()
   * @generated
   */
  EAttribute getparamList_Types();

  /**
   * Returns the meta object for class '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.out <em>out</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>out</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.out
   * @generated
   */
  EClass getout();

  /**
   * Returns the meta object for the containment reference '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.out#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.out#getExp()
   * @see #getout()
   * @generated
   */
  EReference getout_Exp();

  /**
   * Returns the meta object for the attribute '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.out#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.out#getName()
   * @see #getout()
   * @generated
   */
  EAttribute getout_Name();

  /**
   * Returns the meta object for class '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.in <em>in</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>in</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.in
   * @generated
   */
  EClass getin();

  /**
   * Returns the meta object for the attribute '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.in#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.in#getName()
   * @see #getin()
   * @generated
   */
  EAttribute getin_Name();

  /**
   * Returns the meta object for the attribute '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.in#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.in#getType()
   * @see #getin()
   * @generated
   */
  EAttribute getin_Type();

  /**
   * Returns the meta object for class '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.typedExpression <em>typed Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>typed Expression</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.typedExpression
   * @generated
   */
  EClass gettypedExpression();

  /**
   * Returns the meta object for the containment reference '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.typedExpression#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.typedExpression#getExp()
   * @see #gettypedExpression()
   * @generated
   */
  EReference gettypedExpression_Exp();

  /**
   * Returns the meta object for the attribute '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.typedExpression#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.typedExpression#getType()
   * @see #gettypedExpression()
   * @generated
   */
  EAttribute gettypedExpression_Type();

  /**
   * Returns the meta object for class '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.expression <em>expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>expression</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.expression
   * @generated
   */
  EClass getexpression();

  /**
   * Returns the meta object for class '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.value <em>value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>value</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.value
   * @generated
   */
  EClass getvalue();

  /**
   * Returns the meta object for the attribute '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.value#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.value#getOp()
   * @see #getvalue()
   * @generated
   */
  EAttribute getvalue_Op();

  /**
   * Returns the meta object for the containment reference '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.value#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.value#getExp()
   * @see #getvalue()
   * @generated
   */
  EReference getvalue_Exp();

  /**
   * Returns the meta object for the containment reference list '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.value#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.value#getStatements()
   * @see #getvalue()
   * @generated
   */
  EReference getvalue_Statements();

  /**
   * Returns the meta object for the attribute '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.value#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.value#getName()
   * @see #getvalue()
   * @generated
   */
  EAttribute getvalue_Name();

  /**
   * Returns the meta object for the containment reference list '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.value#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.value#getArgs()
   * @see #getvalue()
   * @generated
   */
  EReference getvalue_Args();

  /**
   * Returns the meta object for class '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.arg <em>arg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>arg</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.arg
   * @generated
   */
  EClass getarg();

  /**
   * Returns the meta object for the attribute '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.arg#getArg <em>Arg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Arg</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.arg#getArg()
   * @see #getarg()
   * @generated
   */
  EAttribute getarg_Arg();

  /**
   * Returns the meta object for the containment reference '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.arg#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.arg#getExp()
   * @see #getarg()
   * @generated
   */
  EReference getarg_Exp();

  /**
   * Returns the meta object for class '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.IfStatement <em>If Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If Statement</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.IfStatement
   * @generated
   */
  EClass getIfStatement();

  /**
   * Returns the meta object for the containment reference '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.IfStatement#getIf <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>If</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.IfStatement#getIf()
   * @see #getIfStatement()
   * @generated
   */
  EReference getIfStatement_If();

  /**
   * Returns the meta object for the containment reference '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.IfStatement#getThen <em>Then</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Then</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.IfStatement#getThen()
   * @see #getIfStatement()
   * @generated
   */
  EReference getIfStatement_Then();

  /**
   * Returns the meta object for the containment reference '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.IfStatement#getElse <em>Else</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Else</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.IfStatement#getElse()
   * @see #getIfStatement()
   * @generated
   */
  EReference getIfStatement_Else();

  /**
   * Returns the meta object for class '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for the containment reference '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.Operation#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.Operation#getLeft()
   * @see #getOperation()
   * @generated
   */
  EReference getOperation_Left();

  /**
   * Returns the meta object for the attribute '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.Operation#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.Operation#getOp()
   * @see #getOperation()
   * @generated
   */
  EAttribute getOperation_Op();

  /**
   * Returns the meta object for the containment reference '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.Operation#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see de.uniluebeck.isp.tessla.xtext.teSSLa.Operation#getRight()
   * @see #getOperation()
   * @generated
   */
  EReference getOperation_Right();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TeSSLaFactory getTeSSLaFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.ModelImpl
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Spec</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__SPEC = eINSTANCE.getModel_Spec();

    /**
     * The meta object literal for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.StatementImpl
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '<em><b>Def</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__DEF = eINSTANCE.getStatement_Def();

    /**
     * The meta object literal for the '<em><b>Out</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__OUT = eINSTANCE.getStatement_Out();

    /**
     * The meta object literal for the '<em><b>In</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__IN = eINSTANCE.getStatement_In();

    /**
     * The meta object literal for the '<em><b>Comment</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENT__COMMENT = eINSTANCE.getStatement_Comment();

    /**
     * The meta object literal for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.definitionImpl <em>definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.definitionImpl
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#getdefinition()
     * @generated
     */
    EClass DEFINITION = eINSTANCE.getdefinition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFINITION__NAME = eINSTANCE.getdefinition_Name();

    /**
     * The meta object literal for the '<em><b>Param List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__PARAM_LIST = eINSTANCE.getdefinition_ParamList();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFINITION__TYPE = eINSTANCE.getdefinition_Type();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__EXPRESSION = eINSTANCE.getdefinition_Expression();

    /**
     * The meta object literal for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.paramListImpl <em>param List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.paramListImpl
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#getparamList()
     * @generated
     */
    EClass PARAM_LIST = eINSTANCE.getparamList();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM_LIST__PARAMS = eINSTANCE.getparamList_Params();

    /**
     * The meta object literal for the '<em><b>Types</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM_LIST__TYPES = eINSTANCE.getparamList_Types();

    /**
     * The meta object literal for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.outImpl <em>out</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.outImpl
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#getout()
     * @generated
     */
    EClass OUT = eINSTANCE.getout();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OUT__EXP = eINSTANCE.getout_Exp();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUT__NAME = eINSTANCE.getout_Name();

    /**
     * The meta object literal for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.inImpl <em>in</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.inImpl
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#getin()
     * @generated
     */
    EClass IN = eINSTANCE.getin();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IN__NAME = eINSTANCE.getin_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IN__TYPE = eINSTANCE.getin_Type();

    /**
     * The meta object literal for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.typedExpressionImpl <em>typed Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.typedExpressionImpl
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#gettypedExpression()
     * @generated
     */
    EClass TYPED_EXPRESSION = eINSTANCE.gettypedExpression();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPED_EXPRESSION__EXP = eINSTANCE.gettypedExpression_Exp();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPED_EXPRESSION__TYPE = eINSTANCE.gettypedExpression_Type();

    /**
     * The meta object literal for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.expressionImpl <em>expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.expressionImpl
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#getexpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getexpression();

    /**
     * The meta object literal for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.valueImpl <em>value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.valueImpl
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#getvalue()
     * @generated
     */
    EClass VALUE = eINSTANCE.getvalue();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUE__OP = eINSTANCE.getvalue_Op();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VALUE__EXP = eINSTANCE.getvalue_Exp();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VALUE__STATEMENTS = eINSTANCE.getvalue_Statements();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUE__NAME = eINSTANCE.getvalue_Name();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VALUE__ARGS = eINSTANCE.getvalue_Args();

    /**
     * The meta object literal for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.argImpl <em>arg</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.argImpl
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#getarg()
     * @generated
     */
    EClass ARG = eINSTANCE.getarg();

    /**
     * The meta object literal for the '<em><b>Arg</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARG__ARG = eINSTANCE.getarg_Arg();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARG__EXP = eINSTANCE.getarg_Exp();

    /**
     * The meta object literal for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.IfStatementImpl <em>If Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.IfStatementImpl
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#getIfStatement()
     * @generated
     */
    EClass IF_STATEMENT = eINSTANCE.getIfStatement();

    /**
     * The meta object literal for the '<em><b>If</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_STATEMENT__IF = eINSTANCE.getIfStatement_If();

    /**
     * The meta object literal for the '<em><b>Then</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_STATEMENT__THEN = eINSTANCE.getIfStatement_Then();

    /**
     * The meta object literal for the '<em><b>Else</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_STATEMENT__ELSE = eINSTANCE.getIfStatement_Else();

    /**
     * The meta object literal for the '{@link de.uniluebeck.isp.tessla.xtext.teSSLa.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.OperationImpl
     * @see de.uniluebeck.isp.tessla.xtext.teSSLa.impl.TeSSLaPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION__LEFT = eINSTANCE.getOperation_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION__OP = eINSTANCE.getOperation_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION__RIGHT = eINSTANCE.getOperation_Right();

  }

} //TeSSLaPackage
