/**
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.xtext.ui;

import de.uniluebeck.isp.tessla.xtext.ui.AbstractTeSSLaUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TeSSLaUiModule extends AbstractTeSSLaUiModule {
  public TeSSLaUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
