/*
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.xtext.parser.antlr;

import com.google.inject.Inject;
import de.uniluebeck.isp.tessla.xtext.parser.antlr.internal.InternalTeSSLaParser;
import de.uniluebeck.isp.tessla.xtext.services.TeSSLaGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class TeSSLaParser extends AbstractAntlrParser {

	@Inject
	private TeSSLaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTeSSLaParser createParser(XtextTokenStream stream) {
		return new InternalTeSSLaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public TeSSLaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TeSSLaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
