/**
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.xtext.validation;

import de.uniluebeck.isp.tessla.xtext.validation.AbstractTeSSLaValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TeSSLaValidator extends AbstractTeSSLaValidator {
}
