/**
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.xtext;

import de.uniluebeck.isp.tessla.xtext.AbstractTeSSLaRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TeSSLaRuntimeModule extends AbstractTeSSLaRuntimeModule {
}
