/**
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.xtext.scoping;

import de.uniluebeck.isp.tessla.xtext.scoping.AbstractTeSSLaScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class TeSSLaScopeProvider extends AbstractTeSSLaScopeProvider {
}
