/*
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.xtext.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class TeSSLaScopeProvider extends AbstractTeSSLaScopeProvider {

}
