/*
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractTeSSLaValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(de.uniluebeck.isp.tessla.xtext.teSSLa.TeSSLaPackage.eINSTANCE);
		return result;
	}
	
}
