/*
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TeSSLaRuntimeModule extends AbstractTeSSLaRuntimeModule {
}
