/*
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TeSSLaStandaloneSetup extends TeSSLaStandaloneSetupGenerated {

	def static void doSetup() {
		new TeSSLaStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
