/*
 * generated by Xtext 2.12.0
 */
package de.uniluebeck.isp.tessla.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTeSSLaScopeProvider extends DelegatingScopeProvider {
}
